/**
 * B3: Controlled icon map — ONLY registry icons are importable.
 *
 * This file imports exactly the lucide-react icons listed in amenity-icons.ts registry.
 * DynamicIcon reads from this closed map, not from the full lucide-react namespace.
 * Adding a new icon = add to amenity-icons.ts registry + add import here.
 *
 * Auto-generated from amenity-icons.ts registry keys.
 */

import type { LucideIcon } from "lucide-react";
import {
  Accessibility, AirVent, AlarmClock, Anchor, Apple, Archive,
  Armchair, Award, Baby, BadgeCheck, Ban, Banknote,
  Bath, BedDouble, BedSingle, Beer, Bell, Bike,
  Blinds, Bluetooth, BookOpen, Bus, Cable, Cake,
  CalendarCheck, Car, CarFront, Cat, Cctv, CheckCircle,
  ChefHat, Cigarette, CigaretteOff, CircleHelp, CircleParkingOff, ClipboardList,
  Clock, Cloud, Coffee, Compass, ConciergeBell, CookingPot,
  CreditCard, CupSoda, Dice5, Dog, DoorClosed, DoorOpen,
  Droplets, Dumbbell, Egg, Eye, Fan, Fence,
  FireExtinguisher, Fish, Flag, Flame, FlameKindling, Flower,
  Flower2, Footprints, Fuel, Gamepad2, Gift, GlassWater,
  Goal, Grape, Hand, HandHelping, Headphones, Heart,
  Home, Info, Key, KeyRound, Lamp, LampDesk,
  Laptop, Leaf, Lightbulb, Lock, Mail, Map,
  MapPin, Maximize, Microwave, Minimize, Monitor, Moon,
  Mountain, MountainSnow, Music, Navigation, Newspaper, Package,
  Palmtree, ParkingMeter, PawPrint, Phone, Pipette, Pizza,
  Plane, Plug, PlugZap, Printer, Projector, Puzzle,
  Radio, Rainbow, Receipt, Refrigerator, Route, Ruler,
  Sailboat, Salad, Sandwich, Scissors, Shield, ShieldCheck,
  Ship, Shirt, ShoppingCart, ShowerHead, Signal, Siren,
  Smartphone, Snowflake, Sofa, Sparkles, Speaker, SprayCan,
  Star, Stethoscope, Store, Sun, Sunrise, Sunset,
  Swords, TabletSmartphone, Target, Tent, TentTree, Thermometer,
  ThermometerSnowflake, ThermometerSun, TrainFront, TreeDeciduous, TreePine, Trees,
  Trophy, Truck, Tv, UserCheck, Users, Utensils,
  Volume2, Warehouse, WashingMachine, Waves, Wheat, Wifi,
  Wind, Wine, Zap,
} from "lucide-react";

/** Closed map: kebab-case key → lucide component. Only registry icons. */
export const ICON_MAP: Record<string, LucideIcon> = {
  "accessibility": Accessibility,
  "air-vent": AirVent,
  "alarm-clock": AlarmClock,
  "anchor": Anchor,
  "apple": Apple,
  "archive": Archive,
  "armchair": Armchair,
  "award": Award,
  "baby": Baby,
  "badge-check": BadgeCheck,
  "ban": Ban,
  "banknote": Banknote,
  "bath": Bath,
  "bed-double": BedDouble,
  "bed-single": BedSingle,
  "beer": Beer,
  "bell": Bell,
  "bike": Bike,
  "blinds": Blinds,
  "bluetooth": Bluetooth,
  "book-open": BookOpen,
  "bus": Bus,
  "cable": Cable,
  "cake": Cake,
  "calendar-check": CalendarCheck,
  "car": Car,
  "car-front": CarFront,
  "cat": Cat,
  "cctv": Cctv,
  "check-circle": CheckCircle,
  "chef-hat": ChefHat,
  "cigarette": Cigarette,
  "cigarette-off": CigaretteOff,
  "circle-help": CircleHelp,
  "circle-parking-off": CircleParkingOff,
  "clipboard-list": ClipboardList,
  "clock": Clock,
  "cloud": Cloud,
  "coffee": Coffee,
  "compass": Compass,
  "concierge-bell": ConciergeBell,
  "cooking-pot": CookingPot,
  "credit-card": CreditCard,
  "cup-soda": CupSoda,
  "dice-5": Dice5,
  "dog": Dog,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  "droplets": Droplets,
  "dumbbell": Dumbbell,
  "egg": Egg,
  "eye": Eye,
  "fan": Fan,
  "fence": Fence,
  "fire-extinguisher": FireExtinguisher,
  "fish": Fish,
  "flag": Flag,
  "flame": Flame,
  "flame-kindling": FlameKindling,
  "flower": Flower,
  "flower-2": Flower2,
  "footprints": Footprints,
  "fuel": Fuel,
  "gamepad-2": Gamepad2,
  "gift": Gift,
  "glass-water": GlassWater,
  "goal": Goal,
  "grape": Grape,
  "hand": Hand,
  "hand-helping": HandHelping,
  "headphones": Headphones,
  "heart": Heart,
  "home": Home,
  "info": Info,
  "key": Key,
  "key-round": KeyRound,
  "lamp": Lamp,
  "lamp-desk": LampDesk,
  "laptop": Laptop,
  "leaf": Leaf,
  "lightbulb": Lightbulb,
  "lock": Lock,
  "mail": Mail,
  "map": Map,
  "map-pin": MapPin,
  "maximize": Maximize,
  "microwave": Microwave,
  "minimize": Minimize,
  "monitor": Monitor,
  "moon": Moon,
  "mountain": Mountain,
  "mountain-snow": MountainSnow,
  "music": Music,
  "navigation": Navigation,
  "newspaper": Newspaper,
  "package": Package,
  "palmtree": Palmtree,
  "parking-meter": ParkingMeter,
  "paw-print": PawPrint,
  "phone": Phone,
  "pipette": Pipette,
  "pizza": Pizza,
  "plane": Plane,
  "plug": Plug,
  "plug-zap": PlugZap,
  "printer": Printer,
  "projector": Projector,
  "puzzle": Puzzle,
  "radio": Radio,
  "rainbow": Rainbow,
  "receipt": Receipt,
  "refrigerator": Refrigerator,
  "route": Route,
  "ruler": Ruler,
  "sailboat": Sailboat,
  "salad": Salad,
  "sandwich": Sandwich,
  "scissors": Scissors,
  "shield": Shield,
  "shield-check": ShieldCheck,
  "ship": Ship,
  "shirt": Shirt,
  "shopping-cart": ShoppingCart,
  "shower-head": ShowerHead,
  "signal": Signal,
  "siren": Siren,
  "smartphone": Smartphone,
  "snowflake": Snowflake,
  "sofa": Sofa,
  "sparkles": Sparkles,
  "speaker": Speaker,
  "spray-can": SprayCan,
  "star": Star,
  "stethoscope": Stethoscope,
  "store": Store,
  "sun": Sun,
  "sunrise": Sunrise,
  "sunset": Sunset,
  "swords": Swords,
  "tablet-smartphone": TabletSmartphone,
  "target": Target,
  "tent": Tent,
  "tent-tree": TentTree,
  "thermometer": Thermometer,
  "thermometer-snowflake": ThermometerSnowflake,
  "thermometer-sun": ThermometerSun,
  "train-front": TrainFront,
  "tree-deciduous": TreeDeciduous,
  "tree-pine": TreePine,
  "trees": Trees,
  "trophy": Trophy,
  "truck": Truck,
  "tv": Tv,
  "user-check": UserCheck,
  "users": Users,
  "utensils": Utensils,
  "volume-2": Volume2,
  "warehouse": Warehouse,
  "washing-machine": WashingMachine,
  "waves": Waves,
  "wheat": Wheat,
  "wifi": Wifi,
  "wind": Wind,
  "wine": Wine,
  "zap": Zap,
};
