/**
 * B1 Media types.
 *
 * ResourceImageWithUrls = Prisma ResourceImage + runtime URL fields.
 * URLs are NEVER persisted (ADR-11) — generated from storageKey at read time.
 */

/** Image size variants generated by sharp on upload */
export type ImageSizeVariant = "original" | "medium" | "thumbnail";

/** Prisma ResourceImage extended with runtime URLs */
export interface ResourceImageWithUrls {
  id: string;
  resourceId: string;
  storageKey: string;
  thumbnailKey: string;
  mediumKey: string;
  mimeType: string;
  width: number;
  height: number;
  sizeBytes: number;
  checksum: string;
  alt: string | null;
  position: number;
  isCover: boolean;
  createdAt: string;
  updatedAt: string;
  /** Runtime-generated URLs — not stored in DB */
  urls: {
    original: string;
    medium: string;
    thumbnail: string;
  };
}

/** Upload result returned to frontend after successful upload */
export interface ImageUploadResult {
  image: ResourceImageWithUrls;
}

/** Reorder payload — complete ordered list of image IDs */
export interface ImageReorderPayload {
  imageIds: string[];
}

/** Patch payload — setCover and/or setAlt */
export interface ImagePatchPayload {
  isCover?: boolean;
  alt?: string | null;
}

/** Processing result from image-processor */
export interface ProcessedImage {
  original: Buffer;
  medium: Buffer;
  thumbnail: Buffer;
  width: number;
  height: number;
  sizeBytes: number;
  checksum: string;
  mimeType: "image/webp";
}
